language: node_js # run Node.js
node_js:
  - "8" # Use Node.js v8 (current LTS)
cache:
  directories:
    - node_modules # cache node_modules
    - ~/.npm # cache .npm
    - ~/.cache # cache .cache
yarn: true # use yarn to install dependencies
script: yarn test # run tests
